---
version: '3'
services:
  app:
    build: "."
    command:
    - "./bin/dev"
    volumes:
    - ".:/app"
    ports:
    - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
    - db
    - redis
    links:
    - db
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_app_development
  redis:
    image: redis:7.2
  sidekiq:
    build: "."
    command:
    - bundle
    - exec
    - sidekiq
    volumes:
    - ".:/app"
    depends_on:
    - db
    - redis
    links:
    - db
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
